version: 2
updates:
  - package-ecosystem: "bundler"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "bundler"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "github-actions"