# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
date_format: "%Y-%m-%d"
permalink: none
title: Monkey With A Cupcake
#email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
   I've moved
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://monkeywithacupcake.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
repository: monkeywithacupcake/monkeywithacupcake.github.io
twitter_username: jessachandler
github_username:  monkeywithacupcake

# Build settings
markdown: kramdown
#theme: jekyll-theme-hacker
theme: minima


plugins:
  # - jekyll-feed
  #- jekyll-paginate-v2

# Collections
#collections:
#  round1:
#    output: true
#    longname: "Round 1"
#    description: "Posts from my first trip through 100 Days of Code, started 03 JUL 2017"
#    permalink: /:collection/:path/
#  round2:
#    output: true
#    longname: "Round 2"
#    description: "Posts from my second trip through 100 Days of Code, started 12 OCT 2017"
#    permalink: /:collection/:path/
#
# Plugin: Pagination (jekyll-paginate-v2)
#pagination:
  #collection   :  'round1'
#  enabled      : true
 # debug        : false
 # per_page     : 10
 # permalink    : "/page/:num"
 # #title        : ":title - Page :num of :max"
 # limit        : 0
 # sort_field   : "date"
 # sort_reverse : true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
